/// Flutter icons ScaleIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ScaleIcon
///      fonts:
///       - asset: fonts/ScaleIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ScaleIcon {
  ScaleIcon._();

  static const _kFontFam = 'ScaleIcon';
  static const String? _kFontPkg = null;

  static const IconData scale = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
