// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnQgtAyk90EmjQW8F2xDkblTJ7o2PPwj8',
    appId: '1:626609491474:android:1570c6d4eb31836c5c92cb',
    messagingSenderId: '626609491474',
    projectId: 'trifit-83163',
    storageBucket: 'trifit-83163.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDtfkh9SlnOopVDufO0y0eq-BybJJqq7k',
    appId: '1:626609491474:ios:83de9e6db51e51dc5c92cb',
    messagingSenderId: '626609491474',
    projectId: 'trifit-83163',
    storageBucket: 'trifit-83163.appspot.com',
    iosClientId: '626609491474-m3l0116onrg8muk01g7e11gnh2qipdu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.trifit12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDtfkh9SlnOopVDufO0y0eq-BybJJqq7k',
    appId: '1:626609491474:ios:83de9e6db51e51dc5c92cb',
    messagingSenderId: '626609491474',
    projectId: 'trifit-83163',
    storageBucket: 'trifit-83163.appspot.com',
    iosClientId: '626609491474-m3l0116onrg8muk01g7e11gnh2qipdu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.trifit12',
  );
}
